# Generated by Django 5.2.5 on 2025-09-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_role_solicitudferia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('preferencias', models.TextField(blank=True)),
                ('ocupados', models.IntegerField(default=0)),
            ],
        ),
    ]
