# Generated by Django 5.2 on 2025-09-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_artesano_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesano',
            name='tipo',
        ),
    ]
