# Generated by Django 5.2 on 2025-09-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_artesano_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ferias_favoritas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_favoritos', to='main.feria'),
        ),
    ]
